function Spinner() {
    return <>
        <div className="w-100% h-600px ms-4">
        <div className="loadingio-spinner-ball-dloufnq9tc5">
            <div className="ldio-rl4w9a1u73h">
                <div />
            </div>
        </div>
        <h3 style={{color:'white'}}>Please Wait ....</h3>
        </div>
        <style
            type="text/css"
            dangerouslySetInnerHTML={{
                __html:
                    "\n@keyframes ldio-rl4w9a1u73h {\n  0%, 100% {\n    animation-timing-function: cubic-bezier(0.45,0,0.9,0.55)\n  }\n  0% {\n    transform: translate(0,0)\n  }\n  50% {\n    transform: translate(0,90.5px);\n    animation-timing-function: cubic-bezier(0,0.45,0.55,0.9);\n  }\n  100% {\n    transform: translate(0,0);\n  }\n}\n\n.ldio-rl4w9a1u73h div {\n  position: absolute;\n  width: 54.300000000000004px;\n  height: 54.300000000000004px;\n  border-radius: 50%;\n  background: #f07c29;\n  left: 63.35px;\n  top: 18.1px;\n  animation: ldio-rl4w9a1u73h 2.2222222222222223s linear infinite;\n}\n.loadingio-spinner-ball-dloufnq9tc5 {\n  width: 181px;\n  height: 181px;\n  display: inline-block;\n  overflow: hidden;\n  background: none;\n}\n.ldio-rl4w9a1u73h {\n  width: 100%;\n  height: 100%;\n  position: relative;\n  transform: translateZ(0) scale(1);\n  backface-visibility: hidden;\n  transform-origin: 0 0; /* see note above */\n}\n.ldio-rl4w9a1u73h div { box-sizing: content-box; }\n/* generated by https://loading.io/ */\n"
            }}
        />
    </>
}
export default Spinner;