export const apiEndPoint = {
    CATEGORY_API : "/category/list",
    STATE_API :"/state/stateList",
    FETCH_CITY_BY_STATE:"/city/findCityByState",
    TOP_PRODUCT_API:"/book/topBooks",
    CITY_API:"/city/findCityByState",
    VERIFY_API : "/user/verifyEmail",
    FREE_BOOK_API:"http://localhost:3000/book/freebooklist",
    BOOK_BY_CATEGORY :"book/searchByCategoryId",
    USER_SIGNIN:"/user/signIn",
    USER_SIGNUP:"/user/signup",
    USER_VERIFY : "/user/verifyEmail",
    FORGOTT_PASSWORD : '/user/forgettpassword',
    USER_CHECK : "/user/checkuser",
    USER_UPDATEPROFILE:"/user/updateProfile",
    Search_By_Categoryname: "/book/searchByCategoryId",
    SEARCH_BY_AUTHER: "/book/searchbyAuthor",
    ALL_BOOKS:"/book/list",
    TOTAL_BOOKS:"/book/totalbook",
    RECENT_PRODUCT: '/product/recent-product',
    PRODUCT_LIST: '/product/list',
    FETCH_CART: '/cart/fetchCart',
    ADD_TO_CART: '/cart/addToCart',
    USER_CART : "/cart/userCart",
    UPLOAD_BOOK : "/book/add",
    //ADD_BOOK : "/book/add",
    ADD_BOOK: "http://localhost:3000/book/add",
    SEARCH_BOOKS : "/book/searchByKeyword",
    // FETCH_CITY_BY_STATE:"/city/findCityByState",
    DISK_STORAGE : "http://localhost:3000", //this may be the reason of the error
    REMOVE_CART:"/cart/remove",
    ORDER_SAVE:"/order/saveorder",
    UPDATE_BOOK:"/book/update-book",
    SEARCH_CITY_BY_ID: "/city/byId",
    SEARCH_BOOK_BY_USERID: "/book/serachByuserId",
    FETCH_ORDER:"/order/vieworderByuserId",
    FETCH_ORDER_BY_ORDERID:"/order/vieworderByorderId",
    PRICE: "/book/price",
    DONETORS: "http://localhost:3000/book/donetors",
    ORDER_INVOICE : '/user/invoice'
}
